project_id = "iwxlatqpasvbdfsncyxl"

[functions.graph-data]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.graph-filters]
verify_jwt = false

[functions.graph-analytics]
verify_jwt = false